# Generated by Django 5.0 on 2025-11-11 07:35

import apps.auths.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(db_index=True, help_text="User's email address", max_length=150, unique=True, validators=[apps.auths.validators.validate_email_domain], verbose_name='Email address')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('password', models.CharField(help_text="User's hash representation of password", max_length=254, verbose_name='Password')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Active status')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active status')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('phone', models.CharField(max_length=150, verbose_name="User's Phone number")),
                ('city', models.CharField(max_length=254, verbose_name='City')),
                ('country', models.CharField(max_length=254, verbose_name='Country')),
                ('department', models.CharField(max_length=254, verbose_name='Department')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=254, verbose_name='Role')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salary of User')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Joined Date')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'ordering': ['created_at'],
            },
        ),
    ]
